### ISSUE TITLE
Can not build simpl4, because missing jsstrip.sh

### ISSUE THREAD

**Issue by michaeldoehler** [ms123s/simpl4-src#1]
Hello,

i've checked out a fresh instance from master and execute gradlew.

The system stopped with this message:

FAILURE: Build failed with an exception.

* Where:
Build file '/srv/simpl4/build.gradle' line: 208

* What went wrong:
A problem occurred evaluating project ':surface/js'.
> A problem occurred starting process 'command '/opt/dev/tools/bin/jsstrip.sh''

The path is hardcoded here:
https://github.com/ms123s/simpl4-src/blob/20210e73928568f8d5c2ffbc6d28452db2c21086/surface/js/build.gradle#L47

Where i can find the jsstrip.sh ?

Thanks
Michael

**Comment by ms123s** [comment]
Thanks.

 jsstrip and some other things are now in this repo.
But maybe wait a day,
I check the complete build process again

**Comment by michaeldoehler** [comment]
I pulled from the master and the problem is solved. Thanks!
