### ISSUE TITLE
can't compile with actual repo

### ISSUE THREAD

**Issue by BogusCurry** [ms123s/simpl4-src#3]
hi there ;D

I have clone and compile the actual repo, after this comes a error messages

Successfully started process 'command '/bin/sh''
/bin/sh: 1: make-all.sh: not found
:surface/domelements:buildHtml FAILED
:surface/domelements:buildHtml (Thread[Daemon Thread 3,5,main]) completed. Took 0.015 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':surface/domelements:buildHtml'.
> Process 'command '/bin/sh'' finished with non-zero exit value 127

Can you this fixed or I have make wrong ?

Orcale Java8 installed under Ubuntu 14.04 Server

Greetings

Bogus

**Comment by ms123s** [comment]
I haved fixed the problem.
Maybe you try again
